auth_app/config/routes.rb
Rails.application.routes.draw do

  resources :floors

  resources :reservas do
    get 'calcular', to: 'reservas#calcular', on: :collection
    
  end
  
  root :to => 'sessions#login'

  scope "(:locale)", locale: /de|en/ do
  resources :users do
    get 'signup', to: 'users#new', on: :collection
   end
 
    
  end

  resources :sessions, only: [] do

    post 'login_attempt', on: :collection
    get 'home', on: :collection
    get 'logout', on: :collection
    get 'profile', on: :collection
    get 'setting', on: :collection
    get 'administrar_pisos', on: :collection
    get 'administrar_cuentas', on: :collection
    
  end

end

auth_app/app/models/floor.rb
class Floor < ActiveRecord::Base
end

auth_app/app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: [:show, :edit, :update, :destroy]

  # GET /floors
  # GET /floors.json
  def index
    if session[:user_id]==1
    @floors = Floor.all
  else
    redirect_to reservas_path()
  end
  end

  # GET /floors/1
  # GET /floors/1.json
  def show
  end

  # GET /floors/new
  def new
    @floor = Floor.new
  end

  # GET /floors/1/edit
  def edit
  end

  # POST /floors
  # POST /floors.json
  def create
    @floor = Floor.new(floor_params)

    respond_to do |format|
      if @floor.save
        format.html { redirect_to @floor, notice: 'Floor was successfully created.' }
        format.json { render :show, status: :created, location: @floor }
      else
        format.html { render :new }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /floors/1
  # PATCH/PUT /floors/1.json
  def update
    respond_to do |format|
      if @floor.update(floor_params)
        format.html { redirect_to @floor, notice: 'Floor was successfully updated.' }
        format.json { render :show, status: :ok, location: @floor }
      else
        format.html { render :edit }
        format.json { render json: @floor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /floors/1
  # DELETE /floors/1.json
  def destroy
    @floor.destroy
    respond_to do |format|
      format.html { redirect_to floors_url, notice: 'Floor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor
      @floor = Floor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def floor_params
      params.require(:floor).permit(:piso, :puestos, :ocupados, :disponibles)
    end
end

auth_app/app/helpers/floors_helper.rb
module FloorsHelper
end

auth_app/app/views/floors/_form.html.erb
<%= form_for(@floor) do |f| %>
  <% if @floor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@floor.errors.count, "error") %> prohibited this floor from being saved:</h2>

      <ul>
      <% @floor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :piso %><br>
    <%= f.number_field :piso %>
  </div>
  <div class="field">
    <%= f.label :puestos %><br>
    <%= f.number_field :puestos %>
  </div>
  <div class="field">
    <%= f.label :ocupados %><br>
    <%= f.number_field :ocupados %>
  </div>
  <div class="field">
    <%= f.label :disponibles %><br>
    <%= f.number_field :disponibles %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

auth_app/app/views/floors/edit.html.erb
<h1>Editing Floor</h1>

<%= render 'form' %>

<%= link_to 'Show', @floor %> |
<%= link_to 'Back', floors_path %>

auth_app/app/views/floors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Floors</h1>

<table>
  <thead>
    <tr>
      <th>Piso</th>
      <th>Puestos</th>
      <th>Ocupados</th>
      <th>Disponibles</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @floors.each do |floor| %>
      <tr>
        <td><%= floor.piso %></td>
        <td><%= floor.puestos %></td>
        <td><%= floor.ocupados %></td>
        <td><%= floor.disponibles %></td>
        <td><%= link_to 'Show', floor %></td>
        <td><%= link_to 'Edit', edit_floor_path(floor) %></td>
        <td><%= link_to 'Destroy', floor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Floor', new_floor_path %>

auth_app/app/views/floors/new.html.erb
<h1>New Floor</h1>

<%= render 'form' %>

<%= link_to 'Back', floors_path %>

auth_app/app/views/floors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Piso:</strong>
  <%= @floor.piso %>
</p>

<p>
  <strong>Puestos:</strong>
  <%= @floor.puestos %>
</p>

<p>
  <strong>Ocupados:</strong>
  <%= @floor.ocupados %>
</p>

<p>
  <strong>Disponibles:</strong>
  <%= @floor.disponibles %>
</p>

<%= link_to 'Edit', edit_floor_path(@floor) %> |
<%= link_to 'Back', floors_path %>