auth_app/config/routes.rb
Rails.application.routes.draw do

  resources :floors

  resources :reservas do
    get 'calcular', to: 'reservas#calcular', on: :collection
    
  end
  
  root :to => 'sessions#login'

  scope "(:locale)", locale: /de|en/ do
  resources :users do
    get 'signup', to: 'users#new', on: :collection
   end
 
    
  end

  resources :sessions, only: [] do

    post 'login_attempt', on: :collection
    get 'home', on: :collection
    get 'logout', on: :collection
    get 'profile', on: :collection
    get 'setting', on: :collection
    get 'administrar_pisos', on: :collection
    get 'administrar_cuentas', on: :collection
    
  end

end

auth_app/app/models/reserva.rb
class Reserva < ActiveRecord::Base
belongs_to :user
validates :numpiso, :presence => true
validates :user_id, :presence => true, :uniqueness => true
end

auth_app/app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
    respond_to do |format|
      format.html { redirect_to reservas_path } #, flash[:success] = "holder updated")
      format.pdf do
        render  :pdf => "show.pdf", :template => 'reservas/show.html.erb'
      end
    end

  end

  def calcular
    if session[:user_id]==2
    Appmailer.factura(@reserva).deliver
    else
      redirect_to home_sessions_path()
    end
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end
  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)
    Appmailer.reserva_exitosa(@reserva).deliver
    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:numpiso, :fecha, :horas, :user_id)
    end
end

auth_app/app/helpers/reservas_helper.rb
module ReservasHelper
end

auth_app/app/views/reservas/_form.html.erb
<%= form_for(@reserva) do |f| %>
  <% if @reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
      <% @reserva.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class= "Sign_Form">
  <div class="field">
    <%= f.label :numpiso %><br>
    <%= f.number_field :numpiso %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :horas %><br>
    <%= f.number_field :horas %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

auth_app/app/views/reservas/calcular.html.erb
<h1>Enviado con exito<h2>

auth_app/app/views/reservas/edit.html.erb
<h1>Editing Reserva</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

auth_app/app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Reservas</h1>
<%if session[:user_id]==2%>
<table class="table">
  <thead>
    <tr>
      <th>Numpiso</th>
      <th>Fecha</th>
      <th>Horas</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.numpiso %></td>
        <td><%= reserva.fecha %></td>
        <td><%= reserva.horas %></td>
        <td><%= reserva.user.username %></td>
        <td><%= link_to 'Calcular Tarifa', :calcular_reservas, class: "nav_links" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%else%>
  <table class="table">
  <thead>
    <tr>
      <th>Numpiso</th>
      <th>Fecha</th>
      <th>Horas</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.numpiso %></td>
        <td><%= reserva.fecha %></td>
        <td><%= reserva.horas %></td>
        <td><%= reserva.user.username %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Esta seguro que desea cancelar su reserva?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Reservar Puesto', new_reserva_path %>
<%end%>

auth_app/app/views/reservas/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', reservas_path %>

auth_app/app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numpiso:</strong>
  <%= @reserva.numpiso %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @reserva.fecha %>
</p>

<p>
  <strong>Horas:</strong>
  <%= @reserva.horas %>
</p>

<p>
  <strong>User:</strong>
  <%= link_to @reserva.user.username, @reserva.user %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>